### ISSUE TITLE
테스트 이슈

### ISSUE THREAD

**Issue by KMUlee** [SystemLatestTech-C/Simple-Game#18]
## 구현이 안된 부분
* 멀티에서 스코어가 구현이 안되어 있음
* 엔딩 부분에서 클릭이나 어떠한 이벤트가 있으면 처음 화면으로 돌아가야 함
* 게임이 끝날 때 소켓 통신을 닫아야 함

#17 a0b99098071f53ed2598983b0db6400ebf7509f1

**Comment by 20191570** [comment]
게임이 끝날 때 소켓 통신 닫기를 위한 코드를 추가 했어요.

**Comment by komorie** [comment]
멀티에서 스코어 구현하고, 결과창 부분에서 클릭으로 처음 화면으로 돌아가는 코드 추가했습니다.
